### ISSUE TITLE
Add DS section to the friend code bot

### ISSUE THREAD

**Issue by ShinoBin** [fl0co/RC24-Bot#83]
Requesting this for a friend

**Comment by larsenv** [comment]
You're supposed to put that in the Games section. We have Wii as a separate section so you can register them with Wii Mail. The 3DS has built-in friend code registering too. The DS nor the DSi has internal friend code exchanges, they are all game-based.

Adding friend codes can be messy since people manage them in different ways, however how I explained it is how it was designed.

I'm not sure why Artuto added labels to this, but I'm gonna close this.

**Comment by ShinoBin** [comment]
Problem is, there's a limit to how many can be added in one section, and someone's managed to mess up the bot by putting too many games into the games section.
